server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: resource_service
            uri: lb://resource-service
            predicates:
              - Path=/resources/**
          - id: song_service
            uri: lb://song-service
            predicates:
              - Path=/songs/**
          - id: kibana-redirect
            uri: http://localhost:5601
            predicates:
              - Path=/kibana/**
            filters:
              - RedirectTo=302, http://localhost:5601

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
